/* Generated by scripts/generate-science-data.js. Do not edit by hand. */
export const SCIENCE_DATA = Object.freeze({
  "schemaVersion": 1,
  "scoringVersion": "3.8",
  "sourceHash": "d81d8b00d583a2ff",
  "source": "Open-Meteo historical archive caches",
  "london": {
    "start": "2022-09-05",
    "end": "2022-09-11",
    "dailyScores": [
      {
        "date": "2022-09-05",
        "score": 27,
        "bestHour": "2-3 PM"
      },
      {
        "date": "2022-09-06",
        "score": 12,
        "bestHour": "3-4 PM"
      },
      {
        "date": "2022-09-07",
        "score": 25,
        "bestHour": "10-11 AM"
      },
      {
        "date": "2022-09-08",
        "score": 30,
        "bestHour": "6-7 PM"
      },
      {
        "date": "2022-09-09",
        "score": 19,
        "bestHour": "6-7 PM"
      },
      {
        "date": "2022-09-10",
        "score": 7,
        "bestHour": "11 AM-12 PM"
      },
      {
        "date": "2022-09-11",
        "score": 0,
        "bestHour": null
      }
    ],
    "bestDate": "2022-09-08",
    "bestScore": 30,
    "bestHour": "6-7 PM",
    "bestSunElevation": 8.8
  },
  "climatology": {
    "start": "2024-01-01",
    "end": "2024-12-31",
    "honolulu": {
      "qualifyingDays": 210,
      "hourCounts": {
        "6": 3,
        "7": 16,
        "8": 14,
        "9": 4,
        "10": 4,
        "14": 4,
        "15": 14,
        "16": 26,
        "17": 34,
        "18": 10
      },
      "monthCounts": {
        "1": 35,
        "2": 6,
        "3": 1,
        "4": 12,
        "5": 27,
        "6": 5,
        "7": 1,
        "8": 7,
        "9": 4,
        "10": 16,
        "11": 8,
        "12": 7
      }
    },
    "phoenix": {
      "qualifyingDays": 31
    }
  },
  "dniComparison": [
    {
      "name": "Honolulu",
      "before": 38.6,
      "after": 52.3
    },
    {
      "name": "Phoenix",
      "before": 5.4,
      "after": 6.3
    }
  ]
});
